services:
  db:
    image: mariadb:10.6
    container_name: catenab_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_datab:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: catenab_wp
    restart: always
    ports:
      - "8088:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wp_datab:/var/www/html
      - ./dist:/var/www/html/wp-content/plugins/experiencecrud

  node-builder:
    image: node:18
    container_name: catenab_node
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm run start"


volumes:
  db_datab:
  wp_datab:
